### ISSUE TITLE
4.34.0: Increase in size of compared to previous version

### ISSUE THREAD

**Issue by ElridgeDMello** [pubnub/javascript#228] opened 2021-11-19 23:12 UTC
Hello,

We noticed that there was an order of magnitude in the size of the build for this project.

https://www.npmjs.com/package/pubnub/v/4.33.1 (6.23 MB)
https://www.npmjs.com/package/pubnub/v/4.34.0 (35.9 MB)

We don't use this project directly but it came in as a transitive dependency.  We had to chase down why our build had a dramatic increase between yesterday and today (we deploy to AWS lambda and this size increase pushed our build over the permitted size).

Just wanted to point this out as it might break others too.

Thanks!

**Comment by raipubnub** [comment] 2021-11-19 23:15
Thanks for the info, I will check it out, not sure why that would change so drastically.

**Comment by raipubnub** [comment] 2021-11-20 00:19
@ElridgeDMello This should be resolved in the next release which will be out very soon. This was caused by changes to our deployment process which we didn't realize would end up on NPM :)

**Closed** 2021-11-22 06:35 UTC
